resources:
- name: source-code-from-github
  type: git
  source:
    uri: https://github.com/eddytnk/deploy-springboot-app-using-concourse-ci
    branch: master

jobs:
- name: test-and-build
  public: true
  plan:
  - get: source-code-from-github
    trigger: true
  - task: run-test-and-build-jar-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
      inputs:
      - name: source-code-from-github
      outputs:
      - name: built-jar-file
      caches:
      - path: source-code-from-github/.m2
      run:
        path: sh
        args:
        - -c
        - |
          mvn -f source-code-from-github/pom.xml clean package -Dmaven.repo.local=source-code-from-github/.m2
          cp source-code-from-github/target/*.jar built-jar-file
      #- put: storage
      #    params:
      #     file: built-jar-file/*.jar
      #      name: demo.jar