resources:
- name: source-code-from-github
  type: git
  source:
    uri: https://github.com/eddytnk/deploy-springboot-app-using-concourse-ci
    branch: master

jobs:
- name: test-and-build
  plan:
  - get: source-code-from-github
    trigger: true
  - task: run-test-and-build-jar
    file: source-code-from-github/ci/test-and-build.yml